import json
import re

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from agents.news_agent import news_agent
from services.news_fetcher import fetch_news
from services.email_service import send_email

session_service = InMemorySessionService()


def extract_json(text: str):
    text = text.strip().replace("```json", "").replace("```", "")

    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON found in output:\n{text}")

    return json.loads(match.group())


def format_email_html(date: str, summary_list: list) -> str:
    # Convert list to HTML bullet points
    bullet_html = ""
    if isinstance(summary_list, list):
        bullet_html = "<ul>" + "".join([f"<li>{item}</li>" for item in summary_list]) + "</ul>"
    else:
        bullet_html = f"<p>{summary_list}</p>"
    
    return f"""
    <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6;">
            <h2>Daily Tech News - {date}</h2>
            <hr/>
            {bullet_html}
            <hr/>
            <p style="font-size:12px; color:gray;">
                Generated by your AI News Agent
            </p>
        </body>
    </html>
    """


async def run_daily_news(date: str):
    articles = fetch_news(date)

    print("ARTICLES COUNT:", len(articles))
    print("SAMPLE:", articles[:2])

    runner = Runner(
        app_name="news",
        agent=news_agent,
        session_service=session_service,
    )

    session = await session_service.create_session(
        app_name="news",
        user_id="claire",
    )

    formatted_articles = "\n\n".join([
        f"""
Title: {a['title']}
Source: {a['source']}
Description: {a['description']}
URL: {a['url']}
""" for a in articles
    ])

    prompt = f"""
Summarize these tech news articles for {date}:

{formatted_articles}

Return ONLY valid JSON.
"""

    content = types.Content(
        role="user",
        parts=[types.Part(text=prompt)],
    )

    final_text = ""

    async for event in runner.run_async(
            user_id="claire",
            session_id=session.id,
            new_message=content,
    ):
        if event.is_final_response():
            final_text = event.content.parts[0].text

    if not final_text:
        raise ValueError("Agent returned empty response")

    result = extract_json(final_text)

    # Handle both list and string formats for summary
    summary = result["summary"]
    if isinstance(summary, str):
        # Parse string summary into bullet points
        summary = [s.strip() for s in summary.split("\n") if s.strip()]
    
    html_email = format_email_html(date, summary)
    send_email(html_email)

    return result
